steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: ['build', '-t', 'gcr.io/corpus-451314/corpus-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: push
  waitFor: ['build']
  args: ['push', 'gcr.io/corpus-451314/corpus-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  waitFor: ['push']
  args:
    - run
    - deploy
    - corpus2026
    - --image=gcr.io/corpus-451314/corpus-app
    - --region=europe-west1
    - --platform=managed
    - --set-secrets=DJANGO_SECRET_KEY=DJANGO_SECRET_KEY:latest
    - --set-secrets=DB_NAME=DB_NAME:latest
    - --set-secrets=DB_USER=DB_USER:latest
    - --set-secrets=DB_PASSWORD=DB_PASSWORD:latest
    - --set-secrets=DB_HOST=DB_HOST:latest
    - --set-secrets=DB_PORT=DB_PORT:latest
    - --set-secrets=EMAIL_HOST=EMAIL_HOST:latest
    - --set-secrets=EMAIL_HOST_USER=EMAIL_HOST_USER:latest
    - --set-secrets=EMAIL_HOST_PASSWORD=EMAIL_HOST_PASSWORD:latest
    - --set-secrets=EMAIL_PORT=EMAIL_PORT:latest
    - --set-secrets=STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest
    - --set-secrets=STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY:latest
    - --set-secrets=SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=SOCIAL_AUTH_GOOGLE_OAUTH2_KEY:latest
    - --set-secrets=SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET:latest
    - --update-env-vars=DJANGO_SETTINGS_MODULE=Corpus2026.settings.produccion,EMAIL_USE_TLS=true
    - --allow-unauthenticated


