steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: ['build', '-t', 'gcr.io/corpus-451314/corpus-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: push
  waitFor: ['build']
  args: ['push', 'gcr.io/corpus-451314/corpus-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  waitFor: ['push']
  args:
    - run
    - services
    - update
    - corpus2026
    - --region=europe-west1
    - --image=gcr.io/corpus-451314/corpus-app



