steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/corpus2026-repo/testapp:$COMMIT_SHA',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/corpus2026-repo/testapp:$COMMIT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy testapp \
          --image=europe-west1-docker.pkg.dev/$PROJECT_ID/corpus2026-repo/testapp:$COMMIT_SHA \
          --platform=managed \
          --region=europe-west1 \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
