steps:
# Paso 1: Obtener secretos desde Secret Manager
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'verify-secrets'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Obteniendo secretos..."
      echo "$(gcloud secrets versions access latest --secret=DJANGO_SECRET_KEY)" > /workspace/django_secret_key
      echo "$(gcloud secrets versions access latest --secret=DB_NAME)" > /workspace/db_name
      echo "$(gcloud secrets versions access latest --secret=DB_USER)" > /workspace/db_user
      echo "$(gcloud secrets versions access latest --secret=DB_PASSWORD)" > /workspace/db_password
      echo "$(gcloud secrets versions access latest --secret=DB_HOST)" > /workspace/db_host
      echo "$(gcloud secrets versions access latest --secret=STRIPE_SECRET_KEY)" > /workspace/stripe_secret
      echo "$(gcloud secrets versions access latest --secret=STRIPE_PUBLISHABLE_KEY)" > /workspace/stripe_public
      echo "$(gcloud secrets versions access latest --secret=DJANGO_SETTINGS_MODULE)" > /workspace/django_settings_module

# Paso 2: Construir la imagen
- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  waitFor: ['verify-secrets']
  args: [
    'build',
    '--no-cache',
    '--pull',
    '-t', 'gcr.io/corpus-451314/corpus-app:latest',
    '.'
  ]

# Paso 3: Subir la imagen a Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  id: 'push'
  waitFor: ['build']
  args: [
    'push',
    'gcr.io/corpus-451314/corpus-app:latest'
  ]

# Paso 4: Desplegar a Cloud Run con variables de entorno
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy'
  waitFor: ['push']
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Desplegando a Cloud Run..."
      django_secret_key=$(cat /workspace/django_secret_key)
      db_name=$(cat /workspace/db_name)
      db_user=$(cat /workspace/db_user)
      db_password=$(cat /workspace/db_password)
      db_host=$(cat /workspace/db_host)
      stripe_secret=$(cat /workspace/stripe_secret)
      stripe_public=$(cat /workspace/stripe_public)
      django_settings_module=$(cat /workspace/django_settings_module)

      gcloud run deploy corpus2026 \
        --image=gcr.io/corpus-451314/corpus-app:latest \
        --region=europe-west1 \
        --platform=managed \
        --allow-unauthenticated \
        --add-cloudsql-instances=corpus-451314:europe-west1:corpus-2026-belgium \
        --set-env-vars "DJANGO_SETTINGS_MODULE=$django_settings_module,DJANGO_SECRET_KEY=$django_secret_key,DB_NAME=$db_name,DB_USER=$db_user,DB_PASSWORD=$db_password,DB_HOST=$db_host,STRIPE_SECRET_KEY=$stripe_secret,STRIPE_PUBLISHABLE_KEY=$stripe_public,DEBUG=False,USE_SECRET_MANAGER=true,USE_CLOUD_SQL_PROXY=true,PYTHONPATH=/app,GOOGLE_CLOUD_PROJECT=corpus-451314"

options:
  logging: CLOUD_LOGGING_ONLY   # O el modo que prefieras (NONE, GCS_ONLY, etc)


serviceAccount: '132887978036-compute@developer.gserviceaccount.com' # Cambia por tu cuenta de servicio