# Generated by Django 5.2.4 on 2025-08-07 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('organizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_membresia', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio_membresia', models.DateField(blank=True, null=True)),
                ('fin_membresia', models.DateField(blank=True, null=True)),
                ('membresia_cancelada_en', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='autores/fotos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.CharField(default='miembro', max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='usuarios.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_grupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía de grupo',
                'verbose_name_plural': 'membresías de grupo',
                'unique_together': {('usuario', 'grupo')},
            },
        ),
    ]
