# Generated by Django 5.2.4 on 2025-08-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_drop_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE usuarios_usuario
                      DROP CONSTRAINT IF EXISTS usuarios_usuario_username_key;
                    ALTER TABLE usuarios_usuario
                      DROP COLUMN IF EXISTS username;
                    """,
                    reverse_sql="""
                            ALTER TABLE usuarios_usuario
                              ADD COLUMN username varchar(150);
                            ALTER TABLE usuarios_usuario
                              ADD CONSTRAINT usuarios_usuario_username_key UNIQUE (username);
                            """
                ),
            ],
            state_operations=[
                migrations.RemoveField('usuario', 'username'),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
