# Generated by Django 5.2.4 on 2025-08-29 11:17

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_date_joined_remove_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.Usuario.avatar_upload_path),
        ),
    ]
