# Generated by Django 5.2.4 on 2025-08-07 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('publicaciones', '0001_initial'),
        ('usuarios', '0002_grupo_usuariogrupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='publicaciones.fuente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='propietario_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_grupo', to='usuarios.grupo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='propietario_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_propias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='etiqueta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subetiquetas', to='citas.etiqueta'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='propietario_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_grupo', to='usuarios.grupo'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='propietario_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_propias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='citas', to='citas.etiqueta'),
        ),
    ]
